spring.datasource.url=jdbc:postgresql://db:5432/reopiya_auth_db_prod
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

server.port=8081